-- DOWN MIGRATION: 20251218c_cart_reservation
-- Status: FORWARD-ONLY (restore from snapshot)
--
-- This migration adds cart reservation columns and tables to support WYSIWYG inventory.
-- Rollback via SQL is not recommended because:
--   1. SQLite ALTER TABLE DROP COLUMN requires version 3.35.0+
--   2. Cart reservations may have in-flight state that would be lost
--   3. The cart_rate_limits table would lose abuse prevention data
--
-- ROLLBACK PROCEDURE:
-- 1. Stop the CardMint backend: sudo systemctl stop cardmint-backend
-- 2. Restore the btrfs snapshot taken before deploy:
--    sudo btrfs subvolume delete /var/www/cardmint-backend
--    sudo btrfs subvolume snapshot /snapshots/pre-prod-2025-12-27a /var/www/cardmint-backend
-- 3. OR restore from DB file backup:
--    cp /backups/cardmint_prod.db.pre-2025-12-27a /var/www/cardmint-backend/cardmint_prod.db
-- 4. Rollback code: git checkout prod-2025-12-26 (or previous tag)
-- 5. Restart: sudo systemctl start cardmint-backend
--
-- This file intentionally contains no SQL. The migrate.ts runner skips _down.sql files.
-- It exists solely as documentation for manual rollback procedures.
