#!/usr/bin/env bash

# Controller Environment Setup and Verification Script
# Sets up optimal environment variables for 8BitDo controller integration
# Usage: source ./scripts/controller-env-setup.sh

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CARDMINT_ROOT="$(dirname "$SCRIPT_DIR")"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() {
    echo -e "${BLUE}[Controller Setup]${NC} $*" >&2
}

success() {
    echo -e "${GREEN}✅${NC} $*"
}

warn() {
    echo -e "${YELLOW}⚠️${NC} $*"
}

error() {
    echo -e "${RED}❌${NC} $*"
}

# Auto-detect and set optimal environment variables
setup_controller_env() {
    log "Setting up 8BitDo controller environment variables..."
    
    cd "$CARDMINT_ROOT"
    
    # Try to detect controller and get optimal settings
    local detection_output
    if detection_output=$(npm run gamepad:detect -- --match 8bitdo 2>/dev/null); then
        if echo "$detection_output" | grep -q "READY"; then
            local json_line
            json_line=$(echo "$detection_output" | grep "READY" | sed 's/READY //')
            
            # Parse detection info
            local keyboard_path
            local keyboard_byid
            
            if command -v jq >/dev/null 2>&1; then
                keyboard_path=$(echo "$json_line" | jq -r '.realKeyboardEventPath // .keyboardEventPath // empty')
                keyboard_byid=$(echo "$json_line" | jq -r '.keyboardById // empty')
            else
                # Basic parsing without jq
                keyboard_path=$(echo "$json_line" | grep -o '"realKeyboardEventPath":"[^"]*"' | cut -d'"' -f4)
                if [ -z "$keyboard_path" ]; then
                    keyboard_path=$(echo "$json_line" | grep -o '"keyboardEventPath":"[^"]*"' | cut -d'"' -f4)
                fi
                keyboard_byid=$(echo "$json_line" | grep -o '"keyboardById":"[^"]*"' | cut -d'"' -f4)
            fi
            
            # Set environment variables if we found paths
            if [ -n "$keyboard_path" ] && [ -e "$keyboard_path" ]; then
                export CONTROLLER_KBD_EVENT="$keyboard_path"
                success "Set CONTROLLER_KBD_EVENT=$keyboard_path"
            fi
            
            if [ -n "$keyboard_byid" ] && [ -e "$keyboard_byid" ]; then
                export CONTROLLER_KBD_BYID="$keyboard_byid"
                success "Set CONTROLLER_KBD_BYID=$keyboard_byid"
            fi
            
            # Set debug logging for initial troubleshooting
            export LOG_LEVEL="${LOG_LEVEL:-debug}"
            success "Set LOG_LEVEL=$LOG_LEVEL (controller debugging enabled)"
            
        else
            warn "8BitDo controller not detected. Manual environment setup may be required."
            return 1
        fi
    else
        error "Failed to run gamepad detection. Please check npm dependencies."
        return 1
    fi
}

# Verify environment setup
verify_controller_env() {
    log "Verifying controller environment setup..."
    
    local env_count=0
    
    if [ -n "${CONTROLLER_KBD_EVENT:-}" ]; then
        if [ -e "$CONTROLLER_KBD_EVENT" ]; then
            success "CONTROLLER_KBD_EVENT: $CONTROLLER_KBD_EVENT (exists)"
            env_count=$((env_count + 1))
        else
            error "CONTROLLER_KBD_EVENT: $CONTROLLER_KBD_EVENT (does not exist)"
        fi
    fi
    
    if [ -n "${CONTROLLER_KBD_BYID:-}" ]; then
        if [ -e "$CONTROLLER_KBD_BYID" ]; then
            success "CONTROLLER_KBD_BYID: $CONTROLLER_KBD_BYID (exists)"
            env_count=$((env_count + 1))
            
            # Verify symlink resolution
            local resolved
            if resolved=$(readlink -f "$CONTROLLER_KBD_BYID" 2>/dev/null); then
                success "  → Resolves to: $resolved"
                if [ "$resolved" = "${CONTROLLER_KBD_EVENT:-}" ]; then
                    success "  → Matches CONTROLLER_KBD_EVENT"
                fi
            else
                warn "  → Failed to resolve symlink"
            fi
        else
            error "CONTROLLER_KBD_BYID: $CONTROLLER_KBD_BYID (does not exist)"
        fi
    fi
    
    if [ -n "${LOG_LEVEL:-}" ]; then
        success "LOG_LEVEL: $LOG_LEVEL"
    fi
    
    if [ $env_count -eq 0 ]; then
        warn "No controller environment variables are set. Relying on automatic detection."
    else
        success "Controller environment configured with $env_count override(s)"
    fi
}

# Generate .env entries for persistence
generate_env_file() {
    local env_file="$CARDMINT_ROOT/.env.controller"
    
    log "Generating controller environment file: $env_file"
    
    cat > "$env_file" << EOF
# 8BitDo Controller Environment Configuration
# Generated by controller-env-setup.sh at $(date)
# Source this file or add these to your main .env file

EOF

    if [ -n "${CONTROLLER_KBD_EVENT:-}" ]; then
        echo "CONTROLLER_KBD_EVENT=$CONTROLLER_KBD_EVENT" >> "$env_file"
    fi
    
    if [ -n "${CONTROLLER_KBD_BYID:-}" ]; then
        echo "CONTROLLER_KBD_BYID=$CONTROLLER_KBD_BYID" >> "$env_file"
    fi
    
    if [ -n "${LOG_LEVEL:-}" ]; then
        echo "LOG_LEVEL=$LOG_LEVEL" >> "$env_file"
    fi
    
    cat >> "$env_file" << EOF

# To use these settings:
# 1. Source this file: source $env_file
# 2. Or add to your main .env file: cat $env_file >> .env
# 3. Or export manually: export CONTROLLER_KBD_EVENT=$CONTROLLER_KBD_EVENT
EOF

    success "Environment file generated: $env_file"
    log "To persist these settings, run:"
    log "  source $env_file"
    log "  # or"
    log "  cat $env_file >> .env"
}

# Quick test of controller functionality
test_controller_quick() {
    log "Running quick controller functionality test..."
    
    cd "$CARDMINT_ROOT"
    
    # Test detection
    if npm run gamepad:detect -- --match 8bitdo >/dev/null 2>&1; then
        success "Controller detection working"
    else
        error "Controller detection failed"
        return 1
    fi
    
    # Test event device accessibility
    if [ -n "${CONTROLLER_KBD_EVENT:-}" ]; then
        if timeout 1s evtest "$CONTROLLER_KBD_EVENT" >/dev/null 2>&1; then
            success "Controller event device accessible"
        else
            warn "Controller event device not accessible (may need permissions)"
        fi
    fi
    
    success "Quick controller test completed"
}

# Main function
main() {
    echo "🎮 8BitDo Controller Environment Setup"
    echo "====================================="
    
    # Parse arguments
    local auto_setup=true
    local generate_file=false
    local test_only=false
    
    for arg in "$@"; do
        case $arg in
            --no-auto)
                auto_setup=false
                ;;
            --generate-file)
                generate_file=true
                ;;
            --test-only)
                test_only=true
                auto_setup=false
                ;;
            --help)
                echo "8BitDo Controller Environment Setup"
                echo "Usage: $0 [OPTIONS]"
                echo ""
                echo "Options:"
                echo "  --no-auto       Skip automatic environment detection"
                echo "  --generate-file Generate .env.controller file"
                echo "  --test-only     Only run verification tests"
                echo "  --help          Show this help"
                echo ""
                echo "To use in your shell:"
                echo "  source $0              # Auto-detect and set environment"
                echo "  source $0 --generate-file  # Also create .env.controller"
                echo ""
                exit 0
                ;;
        esac
    done
    
    if [ "$test_only" = true ]; then
        verify_controller_env
        test_controller_quick
        return $?
    fi
    
    # Auto-detect and setup environment
    if [ "$auto_setup" = true ]; then
        if setup_controller_env; then
            echo ""
            verify_controller_env
            echo ""
            test_controller_quick
        else
            warn "Auto-setup failed. You may need to set environment variables manually."
            echo ""
            echo "Manual setup examples:"
            echo "  export CONTROLLER_KBD_EVENT=/dev/input/event16"
            echo "  export CONTROLLER_KBD_BYID=/dev/input/by-id/...-event-kbd"
            echo "  export LOG_LEVEL=debug"
        fi
    else
        verify_controller_env
    fi
    
    # Generate file if requested
    if [ "$generate_file" = true ]; then
        echo ""
        generate_env_file
    fi
    
    echo ""
    success "Controller environment setup completed"
    
    if [ "$auto_setup" = true ] && [ -n "${CONTROLLER_KBD_EVENT:-}" ]; then
        echo ""
        echo "Ready to run CardMint with optimized controller settings:"
        echo "  npm run dev:full"
        echo ""
        echo "Or test controller manually:"
        echo "  ./scripts/test-controller-events.sh --evtest"
    fi
}

# Check if script is being sourced or executed
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
else
    # Being sourced - run setup automatically
    main "$@"
fi